# Generated by Django 6.0.5 on 2026-05-14 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_answered',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_from_admin',
            field=models.BooleanField(default=False, verbose_name='От администратора'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
