# Generated by Django 6.0.5 on 2026-05-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_chatmessage_options_remove_chatmessage_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='discount_text',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image_url',
            field=models.URLField(blank=True, help_text='Если не загружено изображение', verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
